# Generated by Django 5.0.3 on 2024-04-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_topic_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='time',
            field=models.TimeField(default='10:00'),
        ),
    ]
